datazip-inc/olake

- types/data_types.go
- types/stream.go
- typeutils/datatype.go
- typeutils/fields.go
Fixes issue with lack of timestamp precision in the Olake system
> feat: Timestamp precision in DataTypes

- LICENCE
> Update LICENCE to add year and company name

- CONTRIBUTING.md
> chore: Adding CONTRIBUTING.md file

- README.md
cost related info is there on the website, redirecting there
> Update README.md to remove pricing from github

- .gitignore
- build.sh
- drivers/mongodb/internal/backfill.go
- drivers/mongodb/internal/cdc.go
- drivers/mongodb/internal/config.go
- protocol/writers.go
- release-tool.sh
- types/type_schema.go
- typeutils/reformat.go
- writers/local/local.go
> chore: Code Formatting

- README.md
add better user experience navigating olake
> Update README.md to add better user experience navigating olake

- .github/workflows/build-and-release-driver.yml
> chore: Change Docker Repo Name

- drivers/mongodb/README.md
- drivers/mongodb/go.mod
- drivers/mongodb/internal/cdc.go
- drivers/mongodb/internal/config.go
- drivers/mongodb/internal/mon.go
- go.mod
- logger/logger.go
- protocol/root.go
- protocol/sync.go
- types/catalog.go
- types/stream.go
- types/stream_configured.go
- typeutils/reformat.go
- utils/utils.go
Catalog Restructure and Autosave Catalog and State Files
> chore: Catalog Restructure and Autosave Catalog and State Files (#66)

- CONTRIBUTING.md
- README.md
- docker-compose.yml
Added the full 'Getting Started with OLake'
> chore: Readme Update with Getting Started

- CONTRIBUTING.md
- README.md
- docker-compose.yml
Readme Update with Getting Started
> chore: Readme Update with Getting Started (#73)

- README.md
- drivers/mongodb/README.md
- protocol/interface.go
- protocol/sync.go
- protocol/writers.go
- types/catalog.go
- types/stream_configured.go
- typeutils/reformat.go
- utils/utils.go
- writers/parquet/parquet.go
Feature For: https://github.com/datazip-inc/olake/issues/82
> feat: Folder Partition in Parquet Writer

- drivers/mongodb/internal/backfill.go
- drivers/mongodb/internal/cdc.go
- drivers/mongodb/internal/mon.go
- logger/logger.go
- protocol/check.go
- protocol/discover.go
- protocol/interface.go
- protocol/spec.go
- protocol/sync.go
- protocol/writers.go
- types/state.go
- types/stream.go
- types/stream_configured.go
- utils/utils.go
- writers/parquet/parquet.go
> feat: Resumable Full Load In Mongodb (#61)

- drivers/mongodb/internal/backfill.go
- logger/logger.go
- protocol/sync.go
- protocol/writers.go
- types/state.go
> Chore: Adding Stats and Speed Fix

- drivers/mongodb/README.md
- drivers/mongodb/internal/backfill.go
- drivers/mongodb/internal/config.go
> Feat:  Adding Split Vector Strategy In Mongodb (#97)

- types/data_types.go
- types/type_schema.go
- writers/parquet/parquet.go
> chore: Migrating Fraugster to Parquet-Go

- .github/FUNDING.yml
- .github/workflows/build-and-release-driver.yml
- release-tool.sh
Adding releaser from staging to master
> Chore: Merge Staging -> Master

- CONTRIBUTING.md
Fixed Broken link present inside  CONTRIBUTING.md
Fixes Issue: #123
-  This change requires a documentation update
Manually opened the link.
> Fix: Broken Link in  CONTRIBUTING.md

- README.md
- drivers/mongodb/README.md
- drivers/postgres/README.md
Updates
1. Master readme
2. Postgres readme
3. MongoDB readme
> Chore: Update master readme, mongo and postgres readme

- constants/constants.go
- protocol/writers.go
- types/data_types.go
> Hotfix: parquet writer

- drivers/mongodb/internal/cdc.go
- protocol/writers.go
- types/data_types.go
- types/state.go
Currently, MongoDB's delete record ID is not coming to the destination. 
Also, the CDC deleted at not coming in normalized records.
> fix: mongo delete records

- drivers/mongodb/internal/backfill.go
- drivers/mongodb/internal/cdc.go
- drivers/mongodb/internal/mon.go
- drivers/mysql/internal/mysql.go
- drivers/postgres/internal/postgres.go
- types/data_types.go
Fix contains:
-> Discover column reformat
-> Mongodb Primitive types removal from data
> fix: primitive type conversions for mongodb

- .github/workflows/integration-tests.yml
- drivers/base/base_test_utils.go
- go.mod
- go.work
- writers/iceberg/debezium-server-iceberg-sink/dependency-reduced-pom.xml
- writers/iceberg/local-test/Dockerfile
- writers/iceberg/local-test/docker-compose.yml
- writers/iceberg/local-test/spark-defaults.conf
> fix: spark issue

- drivers/mongodb/internal/mon.go
- drivers/mysql/internal/backfill.go
- drivers/mysql/internal/cdc.go
- drivers/postgres/internal/cdc.go
- protocol/sync.go
- types/state.go
> fix(source): full refresh

- drivers/abstract/abstract.go
- drivers/mongodb/README.md
- drivers/mongodb/internal/config.go
- drivers/mongodb/internal/mon.go
- drivers/mysql/README.md
- drivers/mysql/internal/config.go
- drivers/mysql/internal/mysql.go
- drivers/postgres/README.md
- drivers/postgres/internal/config.go
- drivers/postgres/internal/postgres.go
- protocol/discover.go
- protocol/root.go
- protocol/sync.go
- types/catalog.go
- types/stream.go
> feat: discover with merge of old streams.json

- .github/workflows/integration-tests.yml
- README.md
- drivers/abstract/abstract.go
- drivers/abstract/cdc.go
- drivers/mongodb/README.md
- drivers/mongodb/internal/config.go
- drivers/mongodb/internal/mon.go
- drivers/mysql/README.md
- drivers/mysql/internal/config.go
- drivers/mysql/internal/mysql.go
- drivers/postgres/README.md
- drivers/postgres/internal/config.go
- drivers/postgres/internal/postgres.go
- protocol/discover.go
- protocol/root.go
- protocol/sync.go
- types/catalog.go
- types/stream.go
- types/sync_mode.go
Staging to Master merge for Version v0.1.1
> chore: Staging to Master v0.1.1

- destination/iceberg/iceberg_utils.go
- drivers/abstract/abstract.go
- drivers/mysql/internal/backfill.go
- go.mod
- pkg/waljs/waljs.go
- protocol/discover.go
- protocol/root.go
- protocol/sync.go
- utils/concurrent.go
- utils/telemetry/telemetry.go
- utils/utils.go
> chore: Staging to Master v0.1.2

- .github/workflows/release-approval.yml
- .github/workflows/security-ci.yaml
- destination/iceberg/olake-iceberg-java-writer/pom.xml
- drivers/postgres/internal/cdc.go
- pkg/waljs/waljs.go
- protocol/discover.go
- protocol/sync.go
- types/state.go
Due to an LSN mismatch or any other reason, a full load is required. In this case, the previous WAL cache becomes invalid.
We now skip the invalid cache by advancing the LSN at the start of the full load, ensuring we do not read from the invalid cache.
Improvement
> chore: improve postgres cdc

- types/catalog.go
Picking up the cursor field from the old streams file and merging into the new one.
> fix: merge cursor field in new discover

- drivers/oracle/README.md
- drivers/oracle/internal/backfill.go
- drivers/oracle/internal/config.go
- drivers/oracle/internal/oracle.go
- pkg/jdbc/jdbc.go
- As part of extending filter functionality across connectors, this PR adds support to the Oracle connector, enabling the use of `<`, `<=`, `>`, `>=`, `=`, `!=` operators.
- Additionally, this PR significantly improves the chunking strategy for Oracle. Instead of scanning the full table and querying for row boundaries repeatedly, we now leverage Oracle’s native DBMS_PARALLEL_EXECUTE package to generate rowid-based chunks efficiently.
- Other improvements include:
- Updated SQL queries to work under more restrictive permission sets.
- Added support for discovering tables owned by other users, provided the current user has been granted access.
- Fixed connection string handling to support lowercase usernames.
-  Tested all supported filter operators (`<`, `<=`, `>`, `>=`, `=`, `!=`)
- …
> feat: add filter support and optimize chunking strategy for oracle connector

- drivers/abstract/backfill.go
- drivers/abstract/incremental.go
- drivers/mongodb/internal/backfill.go
- drivers/mongodb/internal/incremental.go
- drivers/mysql/internal/mysql.go
- drivers/oracle/internal/incremental.go
- drivers/oracle/internal/oracle.go
- drivers/postgres/internal/postgres.go
- types/type_schema.go
- Extends the functionality of Incremental sync to oracle connector.
- Currently shows and handles the cursor field as it was mentioned in the database be it uppercase, lowercase or mixed case.
- Integer type datatype
- Float/ Number with scale > 0
- String type
> feat: incremental for oracle connector

- destination/writers.go
- drivers/abstract/utils.go
- drivers/mongodb/internal/backfill.go
- drivers/mongodb/internal/mon.go
- types/type_schema.go
- utils/typeutils/fields.go
-> Panic In writer side handled 
-> GetType behaviour fixed (will return only one type using Type Ancestor Tree)
-> Total Number of Records in Mongo typecasting issue fix: https://github.com/datazip-inc/olake/issues/409
> fix: multiple data types and writer panic

- drivers/mongodb/README.md
- drivers/mongodb/internal/backfill.go
- drivers/mongodb/internal/incremental.go
> feat: mongo filter and multi cursor

- CONTRIBUTING.md
- README.md
> fix: slack links

- drivers/mongodb/internal/incremental.go
- pkg/jdbc/jdbc.go
> feat: sync only greater than records in incremental

- drivers/mysql/internal/mysql.go
- drivers/mysql/resources/spec.json
- drivers/postgres/internal/postgres.go
- drivers/postgres/resources/spec.json
- utils/spec/uischema.go
- utils/ssh.go
> fix: tunnel spec

- drivers/mysql/internal/mysql.go
- drivers/mysql/resources/spec.json
- drivers/postgres/internal/postgres.go
- drivers/postgres/resources/spec.json
- types/catalog.go
- utils/spec/uischema.go
- utils/ssh.go
> chore: release version v0.2.3

- .github/pull_request_template.md
- .github/workflows/documentation.yaml
> ci: add workflow to validate doc link for new feature pull request
